### ISSUE TITLE
Clarify implemented Kyber version

### ISSUE THREAD

**Issue by larabr** [dajiaji/crystals-kyber-js#33]
I assume this is implementing version 3 (as opposed to e.g. the NIST version), as that's stated by https://github.com/antontutoveanu/crystals-kyber-javascript . But I didn't find specific info about this.
Is the assumption correct? If so, do you have plans to implement the NIST draft version (https://csrc.nist.gov/pubs/fips/203/ipd)?

**Comment by dajiaji** [comment]
Your assumption is correct, and I also recognized the need to follow the NIST draft (ML-KEM).
However, I still do not understand the difference between v3 and ML-KEM...

**Comment by larabr** [comment]
The differences are listed in page two of the draft 🙂

**Comment by larabr** [comment]
FYI I've implemented the ML-KEM changes [here](https://github.com/openpgpjs/crystals-kyber-js/commit/4bdc3af1cf2e79f146180ed9b7726e443008609f), in case you want to apply them to this repo too (I could also open a PR; we still need to maintain a separate fork to support browsers without native `BigInt`s).

**Comment by dajiaji** [comment]
@larabr Thanks for your information.

Although I'd like you to send a PR to merge your updates including the support for old browsers here, it is probably a tedious work for you, so I will try to merge them to some extent on my end.
